# Generated by Django 3.2.3 on 2021-06-01 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=500)),
                ('cpf', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'client',
            },
        ),
    ]
